name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Build with Gradle
        run: ./gradlew build integrationTest

      - name: Detekt
        run: ./gradlew :mergeDetektSarif
        if: always()
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt

      - name: Create baseline to upload suppressed code-smells to GitHub
        run: ./gradlew deleteDetektBaseline :mergeDetektSarif -PignoreDetektFailures=true
      - name: Upload detekt baseline to Github
        uses: github/codeql-action/upload-sarif@38697555549f1db7851b81482ff19f1fa5c4fedc # v4.34.1
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detektBaseline
