name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/setup-gradle@v6
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Build with Gradle
        run: ./gradlew build integrationTest

      - name: Detekt
        run: ./gradlew :mergeDetektSarif
        if: always()
      - name: Upload SARIF to Github using the upload-sarif action
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detekt

      - name: Create baseline to upload suppressed code-smells to GitHub
        run: ./gradlew deleteDetektBaseline :mergeDetektSarif -PignoreDetektFailures=true
      - name: Upload detekt baseline to Github
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: build/reports/detekt/detekt.sarif
          category: detektBaseline
